[project]
name = "duckdb-polars-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.3",
    "faker>=38.2.0",
    "polars>=1.36.0",
    "psutil>=7.1.3",
    "pyarrow>=22.0.0",
]
